style:
  base: 'seaborn-v0_8-whitegrid'
  
fonts:
  family: 'sans-serif'
  sans-serif: ['Arial']
  size:
    axes_label: 12
    tick_label: 10
    legend: 10
    title: 14

lines:
  width: 2

grid:
  style: '--'
  alpha: 0.5

figure:
  dpi: 300
  save_dpi: 300
  facecolor: 'white'
  axes_facecolor: 'white'

colors:
  background: '#f8f9fa'
  text: '#666666'
  grid: '#cccccc'
  negative: 'red'
  positive: 'blue'
  uncertainty: 'lightgrey'
