# pylint: disable=invalid-name, redefined-builtin, missing-module-docstring
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

import os
import shutil
import sys
from pathlib import Path

# Add project directories to sys.path
# sys.path.insert(0, os.path.abspath('../..'))
sys.path.insert(0, os.path.abspath("../src"))
# sys.path.insert(0, os.path.abspath('../notebooks'))
# sys.path.insert(0, os.path.abspath('../src/calibrated_explanations'))
# sys.path.insert(0, os.path.abspath('../src/calibrated_explanations/utils'))

# Suppress deprecation warnings for docs build
import warnings

warnings.filterwarnings("ignore", category=DeprecationWarning)

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "Calibrated Explanations"
copyright = "2023, Helena Löfström, Tuwe Löfström"
author = "Helena Löfström, Tuwe Löfström"

# The short X.Y version
version = "0.10.2"

# The full version, including alpha/beta/rc tags
release = "0.10.2"

# -- General configuration ---------------------------------------------------

# Sphinx extension module names
extensions = [
    "sphinx.ext.autosummary",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.ifconfig",
    "sphinx.ext.githubpages",
    "numpydoc",
    "nbsphinx",
    "myst_parser",
    "sphinxcontrib.mermaid",
]

# Use the default LaTeX engine to keep Sphinx config validation happy even when we only build HTML
latex_engine = "pdflatex"
latex_elements = {}

# Treat custom section headers used in legacy docstrings as recognised by numpydoc
numpydoc_custom_sections = [
    ("Rules", "Parameters"),
    ("Warning", "Warnings"),
]
# Avoid generating autosummary stubs for every class member; keeps Sphinx -W builds clean
numpydoc_class_members_toctree = False

# The master toctree document
master_doc = "index"

# Intersphinx mapping
intersphinx_mapping = {
    "crepes": ("https://crepes.readthedocs.io/en/latest/", None),
}

# Templates path
templates_path = ["_templates"]

# Language for autogenerated content
language = "en"

# Patterns to ignore when looking for source files
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "_shared/**",
    "improvement/ignore",
    "improvement/archived",
    "improvement/adr_mending",
]

# Skip notebooks that require pandoc when it is unavailable (local CI parity).
if shutil.which("pandoc") is None:
    exclude_patterns.append("improvement/anti_pattern_gap_analysis.ipynb")

# Skip specific GitHub targets that consistently hit rate limits during local linkcheck runs.
linkcheck_ignore = [
    r"https://github.com/Moffran/calibrated_explanations/blob/main/CHANGELOG\.md",
]

# Pygments style for syntax highlighting
pygments_style = "sphinx"

# Enable extended MyST features for directive fences (e.g. mermaid diagrams)
myst_enable_extensions = [
    "colon_fence",
    # Linkify caused spurious detection of code/path fragments as external
    # links (e.g. `DESIGN.md` -> http://DESIGN.md). Disable it and rely
    # on explicit links in the docs instead.
]

# MyST parser configuration: disable fuzzy linkify so plain code/path
# fragments like `external_plugins/shap_lime/DESIGN.md` are not treated
# as external links (which produces false positives in linkcheck).
myst_heading_anchors = 3
myst_config = {
    "linkify_fuzzy_links": False,
}

_SHARED_FRAGMENT_DIR = Path(__file__).parent / "_shared"


def _load_shared_fragment(fragment_name: str) -> str:
    fragment_path = _SHARED_FRAGMENT_DIR / fragment_name
    with fragment_path.open(encoding="utf-8") as fragment_file:
        return fragment_file.read().strip()


# -- Options for HTML output -------------------------------------------------

# HTML theme
html_theme = "furo"

# HTML theme options
html_theme_options = {
    "sidebar_hide_name": False,
    "footer_icons": [
        {
            "name": "GitHub",
            "url": "https://github.com/Moffran/calibrated_explanations",
            "html": "<svg stroke='currentColor' fill='currentColor' stroke-width='0' viewBox='0 0 16 16' height='1.4em' width='1.4em' xmlns='http://www.w3.org/2000/svg'><path fill-rule='evenodd' d='M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z'></path></svg>",
        }
    ],
}

# HTML title
html_title = f"{project} v{version}"

# Last updated format
html_last_updated_fmt = "%b %d, %Y"

# -- Extension configuration -------------------------------------------------

# Source suffixes
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# Autodoc settings
autoclass_content = "init"
autodoc_member_order = "bysource"
autoclass_member_order = "bysource"

# Autosummary settings
autosummary_generate = True
autosummary_imported_members = True

# The todo extension settings
todo_include_todos = True
