name: Dependency Submission
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Detect and submit dependencies
        uses: actions/component-detection-dependency-submission-action@98beaea5a1227f3db476e4c9ca959a0cacd7ac4f
        with:
          detectorsCategories: Python
          detectorsFilter: PipReport
