name: Dependency Submission
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Detect and submit dependencies
        uses: actions/component-detection-dependency-submission-action@98beaea5a1227f3db476e4c9ca959a0cacd7ac4f
        with:
          detectorsCategories: Python
          detectorsFilter: PipReport
