name: ruff
on:
  push:
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'scripts/ci_check_baseline.py'
      - '.github/workflows/ruff.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'pyproject.toml'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install ruff
        run: |
          pip install ruff
      - name: Fail only on new ruff issues (create baseline if missing)
        run: |
          python scripts/ci_check_baseline.py --tool ruff --baseline ci/baselines/ruff.txt --paths src
